'use client';

import PageHeader from '@/components/PageHeader';
import { useLanguage } from '@/contexts/LanguageContext';

export default function TermsPage() {
    const { t, language } = useLanguage();

    return (
        <div className="min-h-screen flex flex-col bg-[var(--bg-primary)]">
            <PageHeader title={language === 'zh' ? '服务条款' : 'Terms of Service'} />

            <main className="flex-1 max-w-4xl mx-auto px-4 py-8 text-[var(--text-primary)]">
                <div className="glass p-8 rounded-2xl border border-[var(--border-subtle)] space-y-8">
                    <div>
                        <h1 className="text-3xl font-bold mb-4">{language === 'zh' ? '服务条款 (Terms of Service)' : 'Terms of Service'}</h1>
                        <p className="text-[var(--text-secondary)]">
                            {language === 'zh'
                                ? '生效日期：2026年1月1日'
                                : 'Effective Date: January 1, 2026'}
                        </p>
                    </div>

                    <div className="prose prose-invert max-w-none text-[var(--text-secondary)] space-y-6">
                        <p className="font-medium text-[var(--text-primary)]">
                            {language === 'zh'
                                ? '请在使用 Human 3.0 网站和服务前仔细阅读这些条款。'
                                : 'Please read these terms carefully before using the Human 3.0 website and services.'}
                        </p>

                        <section className="space-y-3">
                            <h2 className="text-xl font-semibold text-[var(--text-primary)]">
                                {language === 'zh' ? '1. 条款的接受' : '1. Acceptance of Terms'}
                            </h2>
                            <p>
                                {language === 'zh'
                                    ? '访问或使用 Human 3.0 服务，即表示您同意受本服务条款及我们隐私政策的约束。如果您不同意条款的任何部分，则无权访问服务。'
                                    : 'By accessing or using the Human 3.0 Service, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to any part of the terms, you do not have permission to access the Service.'}
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-xl font-semibold text-[var(--text-primary)]">
                                {language === 'zh' ? '2. 服务说明与免责声明' : '2. Service Description and Disclaimer'}
                            </h2>
                            <p>
                                {language === 'zh'
                                    ? 'Human 3.0 提供基于 AI 的个人发展评估。'
                                    : 'Human 3.0 provides AI-based personal development assessments.'}
                            </p>
                            <div className="p-4 bg-[var(--surface-highlight)] rounded-lg border border-[var(--border-subtle)]">
                                <strong className="text-[var(--text-primary)] block mb-2">{language === 'zh' ? '重要免责声明：' : 'IMPORTANT DISCLAIMER:'}</strong>
                                <p className="text-sm">
                                    {language === 'zh'
                                        ? '我们的服务仅供教育和自我提升之用，不构成医疗建议、心理治疗、诊断或专业的心理咨询。服务生成的任何报告、建议或内容均不能替代专业的医疗及心理健康服务。如果您面临心理健康危机，请立即寻求专业医生的帮助。'
                                        : 'Our Service is for educational and self-improvement purposes only and does not constitute medical advice, psychotherapy, diagnosis, or professional counseling. No content generated by the Service should be used as a substitute for professional medical or mental health services. If you are facing a mental health crisis, please seek professional help immediately.'}
                                </p>
                            </div>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-xl font-semibold text-[var(--text-primary)]">
                                {language === 'zh' ? '3. 账户注册与安全' : '3. User Accounts and Security'}
                            </h2>
                            <p>
                                {language === 'zh'
                                    ? '您必须提供准确、完整和最新的注册信息。未能做到这一点将构成对本条款的违反，可能导致您的账户被立即终止。您有责任保护您的密码安全，并对您账户下的所有活动负责。'
                                    : 'You must provide accurate, complete, and current information during registration. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account. You are responsible for safeguarding your password and for all activities under your account.'}
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-xl font-semibold text-[var(--text-primary)]">
                                {language === 'zh' ? '4. 知识产权' : '4. Intellectual Property'}
                            </h2>
                            <p>
                                {language === 'zh'
                                    ? '服务及其原始内容、功能、评估模型和设计仍然是 Human 3.0 及其许可方的专有财产。我们的内容受版权、商标和其他法律的保护。未经我们事先书面同意，不得使用我们的商标。'
                                    : 'The Service and its original content, features, assessment models, and functionality are and will remain the exclusive property of Human 3.0 and its licensors. Our content is protected by copyright, trademark, and other laws. Our trademarks may not be used without our prior written consent.'}
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-xl font-semibold text-[var(--text-primary)]">
                                {language === 'zh' ? '5. 责任限制' : '5. Limitation of Liability'}
                            </h2>
                            <p className="uppercase text-xs font-bold tracking-wider text-[var(--text-muted)]">
                                {language === 'zh' ? '请仔细阅读本节' : 'PLEASE READ THIS SECTION CAREFULLY'}
                            </p>
                            <p>
                                {language === 'zh'
                                    ? '在法律允许的最大范围内，Human 3.0 及其董事、员工、合作伙伴、代理商、供应商或关联公司，在任何情况下均不对以下情况承担责任：(A) 任何间接的、附带的、特殊的、后果性的或惩罚性的损害，包括但不限于利润损失、数据丢失、使用权丧失、商誉损失或其他无形损失；(B) 您访问或使用、或无法访问或使用服务；(C) 服务上的任何第三方内容。无论是否基于保证、合同、侵权（包括疏忽）或其他法律理论。'
                                    : 'TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL HUMAN 3.0, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES, BE LIABLE FOR (A) ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES; (B) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (C) ANY CONTENT OF ANY THIRD PARTY ON THE SERVICE. WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE) OR ANY OTHER LEGAL THEORY.'}
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-xl font-semibold text-[var(--text-primary)]">
                                {language === 'zh' ? '6. 把关与赔偿' : '6. Indemnification'}
                            </h2>
                            <p>
                                {language === 'zh'
                                    ? '您同意赔偿并使 Human 3.0 及其许可方和员工免受因以下原因引起的任何索赔、损害、义务、损失、责任、成本或债务及费用（包括律师费）的损害：(a) 您使用和访问服务；(b) 您违反本条款的任何规定。'
                                    : 'You agree to defend, indemnify and hold harmless Human 3.0 and its licensee and licensors, and their employees, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney\'s fees), resulting from or arising out of a) your use and access of the Service, or b) a breach of these Terms.'}
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-xl font-semibold text-[var(--text-primary)]">
                                {language === 'zh' ? '7. 服务变更与终止' : '7. Termination'}
                            </h2>
                            <p>
                                {language === 'zh'
                                    ? '我们可能会出于任何原因（包括但不限于违反条款）并在不事先通知的情况下，立即终止或暂停您的账户和访问服务的权利。'
                                    : 'We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.'}
                            </p>
                        </section>

                        <section className="space-y-3">
                            <h2 className="text-xl font-semibold text-[var(--text-primary)]">
                                {language === 'zh' ? '8. 适用法律' : '8. Governing Law'}
                            </h2>
                            <p>
                                {language === 'zh'
                                    ? '本条款受新加坡法律管辖并按其解释，不考虑其法律冲突条款。'
                                    : 'These Terms shall be governed and construed in accordance with the laws of Singapore, without regard to its conflict of law provisions.'}
                            </p>
                        </section>

                        <section className="space-y-3 border-t border-[var(--border-subtle)] pt-6 mt-8">
                            <p>
                                {language === 'zh'
                                    ? '如果您对本条款有任何疑问，请联系我们：legal@human3.org'
                                    : 'If you have any questions about these Terms, please contact us at: legal@human3.org'}
                            </p>
                        </section>
                    </div>
                </div>
            </main>
        </div>
    );
}
